#!/bin/sh
export TERM=xterm;

BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
LIME_YELLOW=$(tput setaf 190)
POWDER_BLUE=$(tput setaf 153)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)
BLINK=$(tput blink)
REVERSE=$(tput smso)
UNDERLINE=$(tput smul)

echo "===================================================================================="
echo "                     ${CYAN}         Hello K8s-Play            ${NORMAL}                            "
echo "                                                                                                    "
echo "      ${POWDER_BLUE}                 Welcome to your your Kubernetes Playground               ${NORMAL}                "
echo "${GREEN}"
echo "      .oyyyyyson+.          sh                               hs                                                         "
echo "  .:yhhhhhhhhh/ oy.   .:HHHHhd /:      /: .:HHH:.   :mHHHm.  dh//-  .mmmm. -mHHHm:   -HHHH.   .:HHHH:.                  "
echo "  s.  PPPPPPP nhhh   od/----yd /m:    sd./d+:  \dy       :do dh    .ms          :do dy:      sd/     d+                 "
echo "  hhh.       ohhhh-  m+     sd  om-  +m- hh     oN. -:mmm:ym dy    -N/    -:mmmm:ym N.       my:mmmdh*                  "
echo "  hhh        shhhh:  m+     sd   sd./m/  hh     oN-hh:    ym dy    -N/   .ds    -ms N.       my                         "
echo "  hy ::::::: yhhho   od/---:dh    hdm+   hh     oN-dh:    hh yd:-- -N/   .mo    :mo dy:----  sd:                        "
echo "  / yhhhhhhh-hh+.     .:HHHH:     -Ns    hh     oN  :HHHHH:   :HHH:-N/    .HHHHHH:   -HHHHH.   *HHHH*                   "
echo "   .osyyhhhh+/*                   yy                                                                                    "
echo "${NORMAL}                                                                                                               "
echo "                                                                                    "
echo "  ${CYAN}   General System Information of your SingleNode K8s Cluster                        "
echo
#/usr/bin/screenfetch
echo
echo "System Disk Usage"
inxi -D
echo
echo "${NORMAL}                                                                                                               "
echo "${POWDER_BLUE}Recommended Kubernetes Learning path: ${NORMAL} "
echo "https://dynatrace.sharepoint.com/sites/SE/expertgroups/kubernetes/SitePages/Kubernetes-learning-path.aspx"
echo
echo "${POWDER_BLUE}More information about this Playground: ${NORMAL}"
echo "https://github.com/sergiohinojosa/kubernetes-playground"
echo
echo "${POWDER_BLUE}Apps/Endpoints exposed via Ingress Gateway [kubectl get ing -A]:${NORMAL}"
echo " press [Control] and click on the URL to open the Endpoint in your browser            "
echo "------------------------------------------------------------------------------------${YELLOW}"
#/snap/bin/kubectl get ing -A -o=jsonpath="{range .items[*]}{'-> http://'}{.spec.rules[0].host}{\"\t\"}{\"\n\"}{end}"
/snap/bin/kubectl get ing -A
echo "${NORMAL}------------------------------------------------------------------------------------"
echo " To (un)deploy more apps go to /home/k8splay/apps/ "
echo " example deploy simmplcommerce ${GREEN}cd /home/k8splay/apps/ && bash deploy-simplcommerce.sh${NORMAL} "
echo "------------------------------------------------------------------------------------ "
 

     
