apiVersion: v1
kind: ServiceAccount
metadata:
  name: randomizer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: randomizer
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
      - patch
      - watch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: randomizer
roleRef:
  kind: Role
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: randomizer
spec:
  serviceAccountName: randomizer
  containers:
    - name: randomizer
      image: ghcr.io/mreider/randomizer:latest
      command:
            - node
            - "randomizer.js"
      resources:
        requests:
          cpu: 100m
          memory: 32Mi
        limits:
          memory: 64Mi
          cpu: 100m